//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIPNameEnquiry
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://core.nip.nibss/", ConfigurationName = "NIPNameEnquiry.NIPInterface")]
    public interface NIPInterface
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/fundtransfersingleitem_dcRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/fundtransfersingleitem_dcResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.fundtransfersingleitem_dcResponse> fundtransfersingleitem_dcAsync(NIPNameEnquiry.fundtransfersingleitem_dcRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/fundtransfersingleitem_ddRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/fundtransfersingleitem_ddResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.fundtransfersingleitem_ddResponse> fundtransfersingleitem_ddAsync(NIPNameEnquiry.fundtransfersingleitem_ddRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/txnstatusquerysingleitemRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/txnstatusquerysingleitemResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.txnstatusquerysingleitemResponse> txnstatusquerysingleitemAsync(NIPNameEnquiry.txnstatusquerysingleitemRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/balanceenquiryRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/balanceenquiryResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.balanceenquiryResponse> balanceenquiryAsync(NIPNameEnquiry.balanceenquiryRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/nameenquirysingleitemRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/nameenquirysingleitemResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.nameenquirysingleitemResponse> nameenquirysingleitemAsync(NIPNameEnquiry.nameenquirysingleitemRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/amountblockRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/amountblockResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.amountblockResponse> amountblockAsync(NIPNameEnquiry.amountblockRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/amountunblockRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/amountunblockResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.amountunblockResponse> amountunblockAsync(NIPNameEnquiry.amountunblockRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/accountblockRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/accountblockResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.accountblockResponse> accountblockAsync(NIPNameEnquiry.accountblockRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/accountunblockRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/accountunblockResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.accountunblockResponse> accountunblockAsync(NIPNameEnquiry.accountunblockRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/adjustNIPSettingsRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/adjustNIPSettingsResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.adjustNIPSettingsResponse> adjustNIPSettingsAsync(NIPNameEnquiry.adjustNIPSettingsRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/mandateadviceRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/mandateadviceResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.mandateadviceResponse> mandateadviceAsync(NIPNameEnquiry.mandateadviceRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/financialinstitutionlistRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/financialinstitutionlistResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.financialinstitutionlistResponse> financialinstitutionlistAsync(NIPNameEnquiry.financialinstitutionlistRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/fundtransferAdvice_dcRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/fundtransferAdvice_dcResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.fundtransferAdvice_dcResponse> fundtransferAdvice_dcAsync(NIPNameEnquiry.fundtransferAdvice_dcRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/fundtransferAdvice_ddRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/fundtransferAdvice_ddResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.fundtransferAdvice_ddResponse> fundtransferAdvice_ddAsync(NIPNameEnquiry.fundtransferAdvice_ddRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://core.nip.nibss/NIPInterface/privateAdjustmentOfSettingsRequest", ReplyAction = "http://core.nip.nibss/NIPInterface/privateAdjustmentOfSettingsResponse")]
        System.Threading.Tasks.Task<NIPNameEnquiry.privateAdjustmentOfSettingsResponse> privateAdjustmentOfSettingsAsync(NIPNameEnquiry.privateAdjustmentOfSettingsRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class fundtransfersingleitem_dcRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "fundtransfersingleitem_dc", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.fundtransfersingleitem_dcRequestBody Body;

        public fundtransfersingleitem_dcRequest()
        {
        }

        public fundtransfersingleitem_dcRequest(NIPNameEnquiry.fundtransfersingleitem_dcRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class fundtransfersingleitem_dcRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public fundtransfersingleitem_dcRequestBody()
        {
        }

        public fundtransfersingleitem_dcRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class fundtransfersingleitem_dcResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "fundtransfersingleitem_dcResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.fundtransfersingleitem_dcResponseBody Body;

        public fundtransfersingleitem_dcResponse()
        {
        }

        public fundtransfersingleitem_dcResponse(NIPNameEnquiry.fundtransfersingleitem_dcResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class fundtransfersingleitem_dcResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public fundtransfersingleitem_dcResponseBody()
        {
        }

        public fundtransfersingleitem_dcResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class fundtransfersingleitem_ddRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "fundtransfersingleitem_dd", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.fundtransfersingleitem_ddRequestBody Body;

        public fundtransfersingleitem_ddRequest()
        {
        }

        public fundtransfersingleitem_ddRequest(NIPNameEnquiry.fundtransfersingleitem_ddRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class fundtransfersingleitem_ddRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public fundtransfersingleitem_ddRequestBody()
        {
        }

        public fundtransfersingleitem_ddRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class fundtransfersingleitem_ddResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "fundtransfersingleitem_ddResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.fundtransfersingleitem_ddResponseBody Body;

        public fundtransfersingleitem_ddResponse()
        {
        }

        public fundtransfersingleitem_ddResponse(NIPNameEnquiry.fundtransfersingleitem_ddResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class fundtransfersingleitem_ddResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public fundtransfersingleitem_ddResponseBody()
        {
        }

        public fundtransfersingleitem_ddResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class txnstatusquerysingleitemRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "txnstatusquerysingleitem", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.txnstatusquerysingleitemRequestBody Body;

        public txnstatusquerysingleitemRequest()
        {
        }

        public txnstatusquerysingleitemRequest(NIPNameEnquiry.txnstatusquerysingleitemRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class txnstatusquerysingleitemRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public txnstatusquerysingleitemRequestBody()
        {
        }

        public txnstatusquerysingleitemRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class txnstatusquerysingleitemResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "txnstatusquerysingleitemResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.txnstatusquerysingleitemResponseBody Body;

        public txnstatusquerysingleitemResponse()
        {
        }

        public txnstatusquerysingleitemResponse(NIPNameEnquiry.txnstatusquerysingleitemResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class txnstatusquerysingleitemResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public txnstatusquerysingleitemResponseBody()
        {
        }

        public txnstatusquerysingleitemResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class balanceenquiryRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "balanceenquiry", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.balanceenquiryRequestBody Body;

        public balanceenquiryRequest()
        {
        }

        public balanceenquiryRequest(NIPNameEnquiry.balanceenquiryRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class balanceenquiryRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public balanceenquiryRequestBody()
        {
        }

        public balanceenquiryRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class balanceenquiryResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "balanceenquiryResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.balanceenquiryResponseBody Body;

        public balanceenquiryResponse()
        {
        }

        public balanceenquiryResponse(NIPNameEnquiry.balanceenquiryResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class balanceenquiryResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public balanceenquiryResponseBody()
        {
        }

        public balanceenquiryResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class nameenquirysingleitemRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "nameenquirysingleitem", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.nameenquirysingleitemRequestBody Body;

        public nameenquirysingleitemRequest()
        {
        }

        public nameenquirysingleitemRequest(NIPNameEnquiry.nameenquirysingleitemRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class nameenquirysingleitemRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public nameenquirysingleitemRequestBody()
        {
        }

        public nameenquirysingleitemRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class nameenquirysingleitemResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "nameenquirysingleitemResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.nameenquirysingleitemResponseBody Body;

        public nameenquirysingleitemResponse()
        {
        }

        public nameenquirysingleitemResponse(NIPNameEnquiry.nameenquirysingleitemResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class nameenquirysingleitemResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public nameenquirysingleitemResponseBody()
        {
        }

        public nameenquirysingleitemResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class amountblockRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "amountblock", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.amountblockRequestBody Body;

        public amountblockRequest()
        {
        }

        public amountblockRequest(NIPNameEnquiry.amountblockRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class amountblockRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public amountblockRequestBody()
        {
        }

        public amountblockRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class amountblockResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "amountblockResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.amountblockResponseBody Body;

        public amountblockResponse()
        {
        }

        public amountblockResponse(NIPNameEnquiry.amountblockResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class amountblockResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public amountblockResponseBody()
        {
        }

        public amountblockResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class amountunblockRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "amountunblock", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.amountunblockRequestBody Body;

        public amountunblockRequest()
        {
        }

        public amountunblockRequest(NIPNameEnquiry.amountunblockRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class amountunblockRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public amountunblockRequestBody()
        {
        }

        public amountunblockRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class amountunblockResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "amountunblockResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.amountunblockResponseBody Body;

        public amountunblockResponse()
        {
        }

        public amountunblockResponse(NIPNameEnquiry.amountunblockResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class amountunblockResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public amountunblockResponseBody()
        {
        }

        public amountunblockResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class accountblockRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "accountblock", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.accountblockRequestBody Body;

        public accountblockRequest()
        {
        }

        public accountblockRequest(NIPNameEnquiry.accountblockRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class accountblockRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public accountblockRequestBody()
        {
        }

        public accountblockRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class accountblockResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "accountblockResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.accountblockResponseBody Body;

        public accountblockResponse()
        {
        }

        public accountblockResponse(NIPNameEnquiry.accountblockResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class accountblockResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public accountblockResponseBody()
        {
        }

        public accountblockResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class accountunblockRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "accountunblock", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.accountunblockRequestBody Body;

        public accountunblockRequest()
        {
        }

        public accountunblockRequest(NIPNameEnquiry.accountunblockRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class accountunblockRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public accountunblockRequestBody()
        {
        }

        public accountunblockRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class accountunblockResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "accountunblockResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.accountunblockResponseBody Body;

        public accountunblockResponse()
        {
        }

        public accountunblockResponse(NIPNameEnquiry.accountunblockResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class accountunblockResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public accountunblockResponseBody()
        {
        }

        public accountunblockResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class adjustNIPSettingsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "adjustNIPSettings", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.adjustNIPSettingsRequestBody Body;

        public adjustNIPSettingsRequest()
        {
        }

        public adjustNIPSettingsRequest(NIPNameEnquiry.adjustNIPSettingsRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class adjustNIPSettingsRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public adjustNIPSettingsRequestBody()
        {
        }

        public adjustNIPSettingsRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class adjustNIPSettingsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "adjustNIPSettingsResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.adjustNIPSettingsResponseBody Body;

        public adjustNIPSettingsResponse()
        {
        }

        public adjustNIPSettingsResponse(NIPNameEnquiry.adjustNIPSettingsResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class adjustNIPSettingsResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public adjustNIPSettingsResponseBody()
        {
        }

        public adjustNIPSettingsResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class mandateadviceRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "mandateadvice", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.mandateadviceRequestBody Body;

        public mandateadviceRequest()
        {
        }

        public mandateadviceRequest(NIPNameEnquiry.mandateadviceRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class mandateadviceRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public mandateadviceRequestBody()
        {
        }

        public mandateadviceRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class mandateadviceResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "mandateadviceResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.mandateadviceResponseBody Body;

        public mandateadviceResponse()
        {
        }

        public mandateadviceResponse(NIPNameEnquiry.mandateadviceResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class mandateadviceResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public mandateadviceResponseBody()
        {
        }

        public mandateadviceResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class financialinstitutionlistRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "financialinstitutionlist", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.financialinstitutionlistRequestBody Body;

        public financialinstitutionlistRequest()
        {
        }

        public financialinstitutionlistRequest(NIPNameEnquiry.financialinstitutionlistRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class financialinstitutionlistRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public financialinstitutionlistRequestBody()
        {
        }

        public financialinstitutionlistRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class financialinstitutionlistResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "financialinstitutionlistResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.financialinstitutionlistResponseBody Body;

        public financialinstitutionlistResponse()
        {
        }

        public financialinstitutionlistResponse(NIPNameEnquiry.financialinstitutionlistResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class financialinstitutionlistResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public financialinstitutionlistResponseBody()
        {
        }

        public financialinstitutionlistResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class fundtransferAdvice_dcRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "fundtransferAdvice_dc", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.fundtransferAdvice_dcRequestBody Body;

        public fundtransferAdvice_dcRequest()
        {
        }

        public fundtransferAdvice_dcRequest(NIPNameEnquiry.fundtransferAdvice_dcRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class fundtransferAdvice_dcRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public fundtransferAdvice_dcRequestBody()
        {
        }

        public fundtransferAdvice_dcRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class fundtransferAdvice_dcResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "fundtransferAdvice_dcResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.fundtransferAdvice_dcResponseBody Body;

        public fundtransferAdvice_dcResponse()
        {
        }

        public fundtransferAdvice_dcResponse(NIPNameEnquiry.fundtransferAdvice_dcResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class fundtransferAdvice_dcResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public fundtransferAdvice_dcResponseBody()
        {
        }

        public fundtransferAdvice_dcResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class fundtransferAdvice_ddRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "fundtransferAdvice_dd", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.fundtransferAdvice_ddRequestBody Body;

        public fundtransferAdvice_ddRequest()
        {
        }

        public fundtransferAdvice_ddRequest(NIPNameEnquiry.fundtransferAdvice_ddRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class fundtransferAdvice_ddRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public fundtransferAdvice_ddRequestBody()
        {
        }

        public fundtransferAdvice_ddRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class fundtransferAdvice_ddResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "fundtransferAdvice_ddResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.fundtransferAdvice_ddResponseBody Body;

        public fundtransferAdvice_ddResponse()
        {
        }

        public fundtransferAdvice_ddResponse(NIPNameEnquiry.fundtransferAdvice_ddResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class fundtransferAdvice_ddResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public fundtransferAdvice_ddResponseBody()
        {
        }

        public fundtransferAdvice_ddResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class privateAdjustmentOfSettingsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "privateAdjustmentOfSettings", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.privateAdjustmentOfSettingsRequestBody Body;

        public privateAdjustmentOfSettingsRequest()
        {
        }

        public privateAdjustmentOfSettingsRequest(NIPNameEnquiry.privateAdjustmentOfSettingsRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class privateAdjustmentOfSettingsRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string request;

        public privateAdjustmentOfSettingsRequestBody()
        {
        }

        public privateAdjustmentOfSettingsRequestBody(string request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class privateAdjustmentOfSettingsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "privateAdjustmentOfSettingsResponse", Namespace = "http://core.nip.nibss/", Order = 0)]
        public NIPNameEnquiry.privateAdjustmentOfSettingsResponseBody Body;

        public privateAdjustmentOfSettingsResponse()
        {
        }

        public privateAdjustmentOfSettingsResponse(NIPNameEnquiry.privateAdjustmentOfSettingsResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class privateAdjustmentOfSettingsResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string @return;

        public privateAdjustmentOfSettingsResponseBody()
        {
        }

        public privateAdjustmentOfSettingsResponseBody(string @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NIPInterfaceChannel : NIPNameEnquiry.NIPInterface, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NIPInterfaceClient : System.ServiceModel.ClientBase<NIPNameEnquiry.NIPInterface>, NIPNameEnquiry.NIPInterface
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public NIPInterfaceClient() :
                base(NIPInterfaceClient.GetDefaultBinding(), NIPInterfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NIPInterfacePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public NIPInterfaceClient(EndpointConfiguration endpointConfiguration) :
                base(NIPInterfaceClient.GetBindingForEndpoint(endpointConfiguration), NIPInterfaceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public NIPInterfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(NIPInterfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public NIPInterfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(NIPInterfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public NIPInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.fundtransfersingleitem_dcResponse> NIPNameEnquiry.NIPInterface.fundtransfersingleitem_dcAsync(NIPNameEnquiry.fundtransfersingleitem_dcRequest request)
        {
            return base.Channel.fundtransfersingleitem_dcAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.fundtransfersingleitem_dcResponse> fundtransfersingleitem_dcAsync(string request)
        {
            NIPNameEnquiry.fundtransfersingleitem_dcRequest inValue = new NIPNameEnquiry.fundtransfersingleitem_dcRequest();
            inValue.Body = new NIPNameEnquiry.fundtransfersingleitem_dcRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).fundtransfersingleitem_dcAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.fundtransfersingleitem_ddResponse> NIPNameEnquiry.NIPInterface.fundtransfersingleitem_ddAsync(NIPNameEnquiry.fundtransfersingleitem_ddRequest request)
        {
            return base.Channel.fundtransfersingleitem_ddAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.fundtransfersingleitem_ddResponse> fundtransfersingleitem_ddAsync(string request)
        {
            NIPNameEnquiry.fundtransfersingleitem_ddRequest inValue = new NIPNameEnquiry.fundtransfersingleitem_ddRequest();
            inValue.Body = new NIPNameEnquiry.fundtransfersingleitem_ddRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).fundtransfersingleitem_ddAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.txnstatusquerysingleitemResponse> NIPNameEnquiry.NIPInterface.txnstatusquerysingleitemAsync(NIPNameEnquiry.txnstatusquerysingleitemRequest request)
        {
            return base.Channel.txnstatusquerysingleitemAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.txnstatusquerysingleitemResponse> txnstatusquerysingleitemAsync(string request)
        {
            NIPNameEnquiry.txnstatusquerysingleitemRequest inValue = new NIPNameEnquiry.txnstatusquerysingleitemRequest();
            inValue.Body = new NIPNameEnquiry.txnstatusquerysingleitemRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).txnstatusquerysingleitemAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.balanceenquiryResponse> NIPNameEnquiry.NIPInterface.balanceenquiryAsync(NIPNameEnquiry.balanceenquiryRequest request)
        {
            return base.Channel.balanceenquiryAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.balanceenquiryResponse> balanceenquiryAsync(string request)
        {
            NIPNameEnquiry.balanceenquiryRequest inValue = new NIPNameEnquiry.balanceenquiryRequest();
            inValue.Body = new NIPNameEnquiry.balanceenquiryRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).balanceenquiryAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.nameenquirysingleitemResponse> NIPNameEnquiry.NIPInterface.nameenquirysingleitemAsync(NIPNameEnquiry.nameenquirysingleitemRequest request)
        {
            return base.Channel.nameenquirysingleitemAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.nameenquirysingleitemResponse> nameenquirysingleitemAsync(string request)
        {
            NIPNameEnquiry.nameenquirysingleitemRequest inValue = new NIPNameEnquiry.nameenquirysingleitemRequest();
            inValue.Body = new NIPNameEnquiry.nameenquirysingleitemRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).nameenquirysingleitemAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.amountblockResponse> NIPNameEnquiry.NIPInterface.amountblockAsync(NIPNameEnquiry.amountblockRequest request)
        {
            return base.Channel.amountblockAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.amountblockResponse> amountblockAsync(string request)
        {
            NIPNameEnquiry.amountblockRequest inValue = new NIPNameEnquiry.amountblockRequest();
            inValue.Body = new NIPNameEnquiry.amountblockRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).amountblockAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.amountunblockResponse> NIPNameEnquiry.NIPInterface.amountunblockAsync(NIPNameEnquiry.amountunblockRequest request)
        {
            return base.Channel.amountunblockAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.amountunblockResponse> amountunblockAsync(string request)
        {
            NIPNameEnquiry.amountunblockRequest inValue = new NIPNameEnquiry.amountunblockRequest();
            inValue.Body = new NIPNameEnquiry.amountunblockRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).amountunblockAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.accountblockResponse> NIPNameEnquiry.NIPInterface.accountblockAsync(NIPNameEnquiry.accountblockRequest request)
        {
            return base.Channel.accountblockAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.accountblockResponse> accountblockAsync(string request)
        {
            NIPNameEnquiry.accountblockRequest inValue = new NIPNameEnquiry.accountblockRequest();
            inValue.Body = new NIPNameEnquiry.accountblockRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).accountblockAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.accountunblockResponse> NIPNameEnquiry.NIPInterface.accountunblockAsync(NIPNameEnquiry.accountunblockRequest request)
        {
            return base.Channel.accountunblockAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.accountunblockResponse> accountunblockAsync(string request)
        {
            NIPNameEnquiry.accountunblockRequest inValue = new NIPNameEnquiry.accountunblockRequest();
            inValue.Body = new NIPNameEnquiry.accountunblockRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).accountunblockAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.adjustNIPSettingsResponse> NIPNameEnquiry.NIPInterface.adjustNIPSettingsAsync(NIPNameEnquiry.adjustNIPSettingsRequest request)
        {
            return base.Channel.adjustNIPSettingsAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.adjustNIPSettingsResponse> adjustNIPSettingsAsync(string request)
        {
            NIPNameEnquiry.adjustNIPSettingsRequest inValue = new NIPNameEnquiry.adjustNIPSettingsRequest();
            inValue.Body = new NIPNameEnquiry.adjustNIPSettingsRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).adjustNIPSettingsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.mandateadviceResponse> NIPNameEnquiry.NIPInterface.mandateadviceAsync(NIPNameEnquiry.mandateadviceRequest request)
        {
            return base.Channel.mandateadviceAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.mandateadviceResponse> mandateadviceAsync(string request)
        {
            NIPNameEnquiry.mandateadviceRequest inValue = new NIPNameEnquiry.mandateadviceRequest();
            inValue.Body = new NIPNameEnquiry.mandateadviceRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).mandateadviceAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.financialinstitutionlistResponse> NIPNameEnquiry.NIPInterface.financialinstitutionlistAsync(NIPNameEnquiry.financialinstitutionlistRequest request)
        {
            return base.Channel.financialinstitutionlistAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.financialinstitutionlistResponse> financialinstitutionlistAsync(string request)
        {
            NIPNameEnquiry.financialinstitutionlistRequest inValue = new NIPNameEnquiry.financialinstitutionlistRequest();
            inValue.Body = new NIPNameEnquiry.financialinstitutionlistRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).financialinstitutionlistAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.fundtransferAdvice_dcResponse> NIPNameEnquiry.NIPInterface.fundtransferAdvice_dcAsync(NIPNameEnquiry.fundtransferAdvice_dcRequest request)
        {
            return base.Channel.fundtransferAdvice_dcAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.fundtransferAdvice_dcResponse> fundtransferAdvice_dcAsync(string request)
        {
            NIPNameEnquiry.fundtransferAdvice_dcRequest inValue = new NIPNameEnquiry.fundtransferAdvice_dcRequest();
            inValue.Body = new NIPNameEnquiry.fundtransferAdvice_dcRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).fundtransferAdvice_dcAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.fundtransferAdvice_ddResponse> NIPNameEnquiry.NIPInterface.fundtransferAdvice_ddAsync(NIPNameEnquiry.fundtransferAdvice_ddRequest request)
        {
            return base.Channel.fundtransferAdvice_ddAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.fundtransferAdvice_ddResponse> fundtransferAdvice_ddAsync(string request)
        {
            NIPNameEnquiry.fundtransferAdvice_ddRequest inValue = new NIPNameEnquiry.fundtransferAdvice_ddRequest();
            inValue.Body = new NIPNameEnquiry.fundtransferAdvice_ddRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).fundtransferAdvice_ddAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIPNameEnquiry.privateAdjustmentOfSettingsResponse> NIPNameEnquiry.NIPInterface.privateAdjustmentOfSettingsAsync(NIPNameEnquiry.privateAdjustmentOfSettingsRequest request)
        {
            return base.Channel.privateAdjustmentOfSettingsAsync(request);
        }

        public System.Threading.Tasks.Task<NIPNameEnquiry.privateAdjustmentOfSettingsResponse> privateAdjustmentOfSettingsAsync(string request)
        {
            NIPNameEnquiry.privateAdjustmentOfSettingsRequest inValue = new NIPNameEnquiry.privateAdjustmentOfSettingsRequest();
            inValue.Body = new NIPNameEnquiry.privateAdjustmentOfSettingsRequestBody();
            inValue.Body.request = request;
            return ((NIPNameEnquiry.NIPInterface)(this)).privateAdjustmentOfSettingsAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NIPInterfacePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NIPInterfacePort))
            {
                return new System.ServiceModel.EndpointAddress("http://196.6.103.10:86/NIPWS/NIPInterface");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NIPInterfaceClient.GetBindingForEndpoint(EndpointConfiguration.NIPInterfacePort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NIPInterfaceClient.GetEndpointAddress(EndpointConfiguration.NIPInterfacePort);
        }

        public enum EndpointConfiguration
        {

            NIPInterfacePort,
        }
    }
}
